controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Video;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Pages;
use app\models\Category;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use yii\web\HttpException;
error_reporting(E_ALL & ~E_NOTICE);

class AdminController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        if (!\Yii::$app->user->isGuest) {
            if (\Yii::$app->user->identity->users_type != 'admin') {
                return $this->goHome();
            } else {
                return $this->redirect('/admin/category');
            }
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/admin/category');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionPages()
    {
        if (!\Yii::$app->user->isGuest && (\Yii::$app->user->identity->users_type == 'admin')) {
            $request = Yii::$app->request;
            $modelNewPage = new Pages();
            $modelNewPage->scenario = 'addPage';

            if($_POST){
                if(isset($_POST['updatePages'])){
                    $modelPageU = Pages::find()->where(['id' => $_POST['Pages']['id']])->one();
                    $modelPageU->scenario = 'updatePage';
                    $modelPageU->content = $_POST['Pages']['content'];
                    if($modelPageU->save()){
                        Yii::$app->session->setFlash('page_update');
                    }else{
                        Yii::$app->session->setFlash('page_not_update');
                    }
                }elseif(isset($_POST['addPage'])){
                    if ($modelNewPage->load($request->post())) {
                        if($modelNewPage->save()){
                            Yii::$app->session->setFlash('save_page');
                        }else{
                            Yii::$app->session->setFlash('not_save_page');
                        }
                    }
                }
            }

            $modelPages = Pages::find()->all();
            return $this->render('pages',[
                'newPage' => $modelNewPage,
                'modelPages' => $modelPages
            ]);
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionCategory()
    {
        if (!\Yii::$app->user->isGuest && (\Yii::$app->user->identity->users_type == 'admin')) {
                $newCategory = new Category();
                $newCategory->scenario = 'addCategory';

                if ($_POST) {
                    $request = Yii::$app->request;
                    if ($newCategory->load($request->post())) {
                        $newCategory->save();
                    }
                }
                $modelCategory = Category::find()->all();

                $resultCategory = [];
                foreach ($modelCategory as $parentCategory) {
                    if (($parentCategory['parent_id'] == 0) || $parentCategory['parent_id'] == null) {
                        $resultCategory[$parentCategory['id']]['name'] = $parentCategory['name'];
                        foreach ($modelCategory as $firstChild) {
                            if ($firstChild['parent_id'] == $parentCategory['id']) {
                                $resultCategory[$parentCategory['id']][$firstChild['id']]['name'] = $firstChild['name'];
                                foreach ($modelCategory as $lastChild) {
                                    if ($lastChild['parent_id'] == $firstChild['id']) {
                                        $resultCategory[$parentCategory['id']][$firstChild['id']][$lastChild['id']]['name'] = $lastChild['name'];
                                    }
                                }
                            }
                        }
                    }
                }

                $arrayCategory = ArrayHelper::map(Category::find()->all(), 'id', 'name');

                return $this->render('category', [
                    'newCategory' => $newCategory,
                    'arrayCategory' => $arrayCategory,
                    'resultCategory' => $resultCategory,
                ]);
            
        }else{
            throw new HttpException(404);
        }
    }

    public function actionAjaxcategoryupdate()
    {
        $category_name = $_POST['category_name'];
        $category_id = $_POST['category_id'];

        $modelCategory = Category::find()->where(['id' => $category_id])->one();
        $modelCategory->scenario = 'updateCategory';
        $modelCategory->name = $category_name;
        $result = [];
        if ($modelCategory->save()) {
            $result['status'] = 'success';
        } else {
            $result['status'] = 'error';
        }
        echo json_encode($result);
    }

    public function actionCategorydelete($category_id = null)
    {

        $modelCategory = Category::find()->where(['id' => $category_id])->one();

        $result = [];
        if ($modelCategory->delete()) {
            $result['status'] = 'success';
        } else {
            $result['status'] = 'error';
        }
        return $this->redirect('../../../admin/category');
    }

    public function actionVideo()
    {
        if (!\Yii::$app->user->isGuest && (\Yii::$app->user->identity->users_type == 'admin')) {
            $query = new Query;
            $query->select(['*'])
                ->from('video')
                ->where(['status' => 0]);

            $command = $query->createCommand();
            $modelVideos = $command->queryAll();
            return $this->render('video', [
                'modelVideos' => $modelVideos
            ]);
        }else{
            throw new HttpException(404);
        }
    }

    public function actionGetvideoserver()
    {
        $query = new Query;
        $query->select(['*', 'id' => 'video.id', 'categoryName' => 'category.name'])
            ->from('video')
            ->join('LEFT JOIN',
                'users',
                'users.id = video.user_id')
            ->join('LEFT JOIN',
                'category',
                'category.id = video.category_id')
            ->where(['status' => 0]);

        $command = $query->createCommand();
        $modelVideo = $command->queryAll();

        echo json_encode($modelVideo);
    }

    public function actionUploadyoutube()
    {
        //google_api_php_client_autoload();
        $oauthClientID = '952135163741-r00ams6ebtq4049v64i6m1k3dhp3a8pe.apps.googleusercontent.com';
        $oauthClientSecret = '08GJANtyrlozTIBoZt6VWb0F';
        $baseUri = 'http://youtube-upload.dev/';
        $redirectUri = filter_var('http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'], FILTER_SANITIZE_URL);

        define('OAUTH_CLIENT_ID',$oauthClientID);
        define('OAUTH_CLIENT_SECRET',$oauthClientSecret);
        define('REDIRECT_URI',$redirectUri);
        define('BASE_URI',$baseUri);

        session_start();

        $client = new Google_Client();
        $client->setClientId(OAUTH_CLIENT_ID);
        $client->setClientSecret(OAUTH_CLIENT_SECRET);
        $client->setScopes('https://www.googleapis.com/auth/youtube');
        $client->setRedirectUri(REDIRECT_URI);

        // Define an object that will be used to make all API requests.
        $youtube = new Google_Service_YouTube($client);
        $videoFilePath = '';
        $videoTitle = '';
        $videoDesc = '';
        $videoTags = '';
        if(isset($_REQUEST['videoSubmit'])){
            $videoTitle = $_REQUEST['title'];
            $videoDesc = $_REQUEST['description'];
            $videoTags = $_REQUEST['tags'];

            $ds           = DIRECTORY_SEPARATOR;
            $storeFolder  = \Yii::getAlias('@webroot');
            $videoFilePath = $storeFolder.$ds.'video'.$ds.$_REQUEST['video_src'];

            var_dump($videoFilePath);
            exit;
        }




        /*
         * You can acquire an OAuth 2.0 client ID and client secret from the
         * Google Developers Console <https://console.developers.google.com/>
         * For more information about using OAuth 2.0 to access Google APIs, please see:
         * <https://developers.google.com/youtube/v3/guides/authentication>
         * Please ensure that you have enabled the YouTube Data API for your project.
         */



        if (isset($_GET['code'])) {
            if (strval($_SESSION['state']) !== strval($_GET['state'])) {
                die('The session state did not match.');
            }

            $client->authenticate($_GET['code']);
            $_SESSION['token'] = $client->getAccessToken();

views/admin/currentvideo.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\assets\AdmincurrentvideoAsset;

error_reporting(E_ALL & ~E_NOTICE);
AdmincurrentvideoAsset::register($this);
$storeFolder = \Yii::getAlias('@webroot');
require_once $storeFolder . '/src/config.php';

$oauthClientID = '952135163741-r00ams6ebtq4049v64i6m1k3dhp3a8pe.apps.googleusercontent.com';
$oauthClientSecret = '08GJANtyrlozTIBoZt6VWb0F';
$baseUri = 'http://' . $_SERVER['SERVER_NAME'];
$redirectUri = 'http://' . $_SERVER['SERVER_NAME'] . '/admin/currentvideo';
//$redirectUri = \Yii::$app->request->referrer;
//return $this->redirect(Yii::$app->request->referrer);
//unset($_SESSION['token']);
define('OAUTH_CLIENT_ID', $oauthClientID);
define('OAUTH_CLIENT_SECRET', $oauthClientSecret);
define('REDIRECT_URI', $redirectUri);
define('BASE_URI', $baseUri);

//unset($_SESSION['token']);
$client = new Google_Client();
$client->setClientId(OAUTH_CLIENT_ID);
$client->setClientSecret(OAUTH_CLIENT_SECRET);
$client->setScopes('https://www.googleapis.com/auth/youtube');
$client->setRedirectUri(REDIRECT_URI);

$youtube = new Google_Service_YouTube($client);

$showForm = true;

if (isset($_GET['code'])) {
    if (strval($_SESSION['state']) !== strval($_GET['state'])) {
        die('The session state did not match.');
    }
    $client->authenticate($_GET['code']);
    $_SESSION['token'] = $client->getAccessToken();
    return \Yii::$app->response->redirect(Url::to(['admin/currentvideo']));
}

if (isset($_SESSION['token'])) {
    $client->setAccessToken($_SESSION['token']);
}


if (isset($_REQUEST['videoSubmit'])) {
    $videoTitle = $_REQUEST['title'];
    $videoDesc = $_REQUEST['description'];
    $playListId = $_REQUEST['playlistId'];
    if ($_REQUEST['video_src']) {
        $videoFilePath = $storeFolder . '/video/' . $_REQUEST['video_src'];

        if ($client->getAccessToken()) {
            try {
                $videoPath = $videoFilePath;

                $snippet = new Google_Service_YouTube_VideoSnippet();
                $snippet->setTitle($videoTitle);
                $snippet->setDescription($videoDesc);

                $snippet->setCategoryId("22");

                $status = new Google_Service_YouTube_VideoStatus();
                $status->privacyStatus = "public";

                $video = new Google_Service_YouTube_Video();
                $video->setSnippet($snippet);
                $video->setStatus($status);

                $chunkSizeBytes = 1 * 1024 * 1024;

                $client->setDefer(true);

                $insertRequest = $youtube->videos->insert("status,snippet", $video);

                $media = new Google_Http_MediaFileUpload(
                    $client,
                    $insertRequest,
                    'video/*',
                    null,
                    true,
                    $chunkSizeBytes
                );
                $media->setFileSize(filesize($videoPath));

                $status = false;
                $handle = fopen($videoPath, "rb");
                while (!$status && !feof($handle)) {
                    $chunk = fread($handle, $chunkSizeBytes);
                    $status = $media->nextChunk($chunk);
                }
                fclose($handle);

                $client->setDefer(false);

                @unlink($videoFilePath);


                $playlistId = $playListId;
                $resourceId = new Google_Service_YouTube_ResourceId();
                $resourceId->setVideoId($status['id']);
                $resourceId->setKind('youtube#video');

                $playlistItemSnippet = new Google_Service_YouTube_PlaylistItemSnippet();
                $playlistItemSnippet->setTitle('First video in the test playlist');
                $playlistItemSnippet->setPlaylistId($playlistId);
                $playlistItemSnippet->setResourceId($resourceId);

                $playlistItem = new Google_Service_YouTube_PlaylistItem();
                $playlistItem->setSnippet($playlistItemSnippet);
                $playlistItemResponse = $youtube->playlistItems->insert(
                    'snippet,contentDetails', $playlistItem, array());


                $model2Video->scenario = 'changeStatus';
                $model2Video->video_src = $status['id'];
                $model2Video->status = 1;
                $model2Video->save();

                setcookie("video_id", '');

                \Yii::$app->mailer->compose(['html' => 'videoUploaded-html'], ['username' => $modelVideo['userName'], 'name' => $modelVideo['name']])
                    ->setFrom([\Yii::$app->params['supportEmail'] => 'baselik.ru'])
                    ->setTo($modelVideo['email'])
                    ->setSubject('baselik.ru - Модерация видео')
                    ->send();

                $showForm = false;
                $htmlBodySuccess .= "<div class=\"video_box videoBoxContent clf\">";
                $htmlBodySuccess .= "<p><h3>Видео успешно загружено.</h3></p><ul>";
                $htmlBodySuccess .= '<embed width="400" height="315" src="https://www.youtube.com/embed/' . $status['id'] . '"></embed>';
                $htmlBodySuccess .= '<li style="margin-top: 15px"><b>Название: </b>' . $status['snippet']['title'] . '</li>';
                $htmlBodySuccess .= '<li style="margin-top: 15px"><b>Описание: </b>' . $status['snippet']['description'] . '</li>';
                $htmlBodySuccess .= '<li style="margin-top: 15px"><a href="' . Url::home() . 'admin/video" class="btn btn-success">Назад ко всем видео</a></li>';
                $htmlBodySuccess .= '</ul>';
                $htmlBodySuccess .= '</div>';

            } catch (Google_ServiceException $e) {
                $htmlBodyNotice .= sprintf('<p>A service error occurred: <code>%s</code></p>',
                    htmlspecialchars($e->getMessage()));
            } catch (Google_Exception $e) {
                $htmlBodyNotice .= sprintf('<p>An client error occurred: <code>%s</code></p>', htmlspecialchars($e->getMessage()));
                $htmlBodyNotice .= 'Please reset session <a href="logout.php">Logout</a>';
            }

            $_SESSION['token'] = $client->getAccessToken();
        }

    }
}
if ($client->getAccessToken()) {
    try {
        // var_dump('Stepan');exit;
        //header("Location: /admin/currentvideo");
        $channelsResponse = $youtube->channels->listChannels('contentDetails', array(
            'mine' => 'true',
        ));

        $playlistItemsResponse = $youtube->playlists->listPlaylists('snippet', array(
            'channelId' => $channelsResponse->items[0]->id,
            'maxResults' => 50
        ));
        $options = '';
        foreach ($playlistItemsResponse->items as $item) {
            $options .= '<option value="' . $item['id'] . '">' . $item['snippet']['title'] . '</option>';
        }

    } catch (Google_ServiceException $e) {
        $htmlBodyNotice .= sprintf('<p>Сталася помилка служби: <code>%s</code></p>',
            htmlspecialchars($e->getMessage()));
    } catch (Google_Exception $e) {
        $htmlBodyNotice .= sprintf('<p>Сталася помилка служби: <code>%s</code></p>', htmlspecialchars($e->getMessage()));
        $htmlBodyNotice .= 'Пожалуйста перезагрузите страницу';
        unset($_SESSION['token']);
        unset($_SESSION['state']);
        unset($_SESSION['google_data']); //Google session data unset
        $client->revokeToken();
        session_destroy();
        $showForm = false;
    }
}


//var_dump(file_get_contents('https://www.googleapis.com/youtube/v3/playlists?part=snippet&channelId=UCkc-yzgnQXFRDRhxJelsyUQ&key=AIzaSyBJHF3o8WiIfGVUb1wmYJSpGVVHrHFq1PU'));

?>
<div class="dashboard-container">

    <div class="container">
        <div id="cssmenu">
            <?php echo $this->render('menu'); ?>
        </div>
        <div class="sub-nav hidden-sm hidden-xs">
            <ul>
                <li>
                    <?php echo HTML::a(\Yii::t('app', '<i class="fa fa-home"></i> Home </a><a> <i class="fa fa-arrow-right"> </i> </a><a style="font-size:15px;padding:0px;">Загрузка на Youtube'), '/admin/', ['class' => 'AdminHomePageLink']); ?>
                </li>
            </ul>
        </div>

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
            <!-- Row Start -->
            <div class="row wrap">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <?php
                    $htmlBody = '';
                    echo $htmlBodySuccess;
                    echo $htmlBodyNotice;

                    // Check to ensure that the access token was successfully acquired.
                    if (!$client->getAccessToken()) {
                        // If the user hasn't authorized the app, initiate the OAuth flow
                        $state = mt_rand();
                        $client->setState($state);
                        $_SESSION['state'] = $state;

                        $authUrl = $client->createAuthUrl();
                        $htmlBody = <<<END
    <div class="video_box videoBoxContent clf">
	    <h3>Требуется Авторизация</h3><br>
	    <p>Вам нужно <a href="$authUrl" class="btn btn-danger">войти <i class="fa fa-youtube" aria-hidden="true"></i></a> перед загрузкой видео.<p>
	</div>
END;
                    }
                    ?>

                    <?php
                    echo $htmlBody;
                    if ($client->getAccessToken()) {
                        ?>
                        <div class="video_box videoBoxContent clf">
                            <?php if ($showForm) { ?>
                                <div class="form-group">
                                    <video id="my_video_1" class="video-js vjs-default-skin" width="640px"
                                           height="267px"
                                           controls preload="none" poster='http://video-js.zencoder.com/oceans-clip.jpg'
                                           data-setup='{ "aspectRatio":"640:267", "playbackRates": [1, 1.5, 2] }'>
                                        <source src="<?= '/video/' . $modelVideo['video_src']; ?>" type='video/mp4'/>
                                    </video>
                                </div>

                                <?php $form = ActiveForm::begin(['id' => 'form-signup',
                                    'action' => Url::home() . 'admin/currentvideo',
                                    'method' => 'POST',
                                    'options' => ['class' => 'form-horizontal'],
                                ]); ?>
                                <div class="form-group">
                                    <label for="title" class="control-label col-sm-2"> Название:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="title" id="title"
                                               value="<?= $modelVideo['userName'] . ' ' . $modelVideo['surname'] . ' - ' . $modelVideo['categoryName']; ?>"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="description" class="control-label col-sm-2"> Описание:</label>
                                    <div class="col-sm-10">
                                        <textarea name="description" class="form-control" id="description" cols="20"
                                                  rows="2"><?= $modelVideo['description']; ?></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="title" class="control-label col-sm-2"> Плейлист:</label>
                                    <div class="col-sm-10">
                                        <select name="playlistId" id="playlistId" class="form-control">
                                            <?= $options; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="hidden" name="video_src" id="videoFile"
                                           value="<?= $modelVideo['video_src']; ?>">
                                    <input name="videoSubmit" class="btn btn-success" type="submit"
                                           value="Загрузить видео">
                                </div>
                                <?php ActiveForm::end();
                            } ?>
                        </div>
                    <?php } ?>

                </div>
            </div>
            <!-- Row End -->

        </div>

    </div>
</div>

views/admin/deletevideo.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use app\models\Video;
use app\assets\AdmindeletevideoAsset;
error_reporting(E_ALL & ~E_NOTICE);

AdmindeletevideoAsset::register($this);


$storeFolder = \Yii::getAlias('@webroot');
require_once $storeFolder . '/src/config.php';

$oauthClientID = '952135163741-r00ams6ebtq4049v64i6m1k3dhp3a8pe.apps.googleusercontent.com';
$oauthClientSecret = '08GJANtyrlozTIBoZt6VWb0F';
$baseUri = 'http://'.$_SERVER['SERVER_NAME'];
$redirectUri = 'http://'.$_SERVER['SERVER_NAME'].'/admin/delete-video';

$showvideos = false;
//$redirectUri = \Yii::$app->request->referrer;
//return $this->redirect(Yii::$app->request->referrer);
//unset($_SESSION['token']);
define('OAUTH_CLIENT_ID', $oauthClientID);
define('OAUTH_CLIENT_SECRET', $oauthClientSecret);
define('REDIRECT_URI', $redirectUri);
define('BASE_URI', $baseUri);

//unset($_SESSION['token']);
$client = new Google_Client();
$client->setClientId(OAUTH_CLIENT_ID);
$client->setClientSecret(OAUTH_CLIENT_SECRET);
$client->setScopes('https://www.googleapis.com/auth/youtube');
$client->setRedirectUri(REDIRECT_URI);

$youtube = new Google_Service_YouTube($client);

$showForm = true;

if (isset($_GET['code'])) {
    if (strval($_SESSION['state']) !== strval($_GET['state'])) {
        die('The session state did not match.');
    }
    $client->authenticate($_GET['code']);
    $_SESSION['token'] = $client->getAccessToken();
    return \Yii::$app->response->redirect(Url::to(['admin/delete-video']));
}

if (isset($_SESSION['token'])) {
    $client->setAccessToken($_SESSION['token']);
}

if ($client->getAccessToken()) {
    
    try {
        $showvideos = true;
        if(isset($_POST['video_src']) && isset($_POST['video_id'])) {
            $delete = $youtube->videos->delete($_POST['video_src']);
            $modelVideoDelete = Video::find()->where(['id'=>$_POST['video_id']])->one();
            $modelVideoDelete->delete();
        }

    } catch (Google_ServiceException $e) {
        $htmlBodyNotice .= sprintf('<p>A service error occurred: <code>%s</code></p>',
            htmlspecialchars($e->getMessage()));
    } catch (Google_Exception $e) {
        $htmlBodyNotice .= sprintf('<p>An client error occurred: <code>%s</code></p>', htmlspecialchars($e->getMessage()));
        $htmlBodyNotice .= 'Please reset session';
        $showvideos = false;
    }

    $_SESSION['token'] = $client->getAccessToken();
}else{
    // If the user hasn't authorized the app, initiate the OAuth flow
    $state = mt_rand();
    $client->setState($state);
    $_SESSION['state'] = $state;

    $authUrl = $client->createAuthUrl();
    $htmlBody = <<<END
    <div class="video_box videoBoxContent clf" style="margin-bottom: 25px;">
        <h3>Требуется Авторизация</h3><br>
        <p>Вам нужно <a href="$authUrl" class="btn btn-danger">войти <i class="fa fa-youtube" aria-hidden="true"></i></a> перед загрузкой видео.<p>
    </div>
END;
}
?>
<div class="dashboard-container">

    <div class="container">
        <div id="cssmenu">
            <?php echo $this->render('menu'); ?>
        </div>
        <div class="sub-nav hidden-sm hidden-xs">
            <ul>
                <li>
                    <?php echo HTML::a(\Yii::t('app', '<i class="fa fa-home"></i> Home </a><a> <i class="fa fa-arrow-right"> </i> </a><a style="font-size:15px;padding:0px;">Загрузка на Youtube'), '/admin/', ['class' => 'AdminHomePageLink']); ?>
                </li>
            </ul>
        </div>

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
            <!-- Row Start -->
            <div class="row wrap">
                <div class="video_box videoBoxContent clf">
                    <p class="reklab_art">Видео на удаление</p>
                    <?=$htmlBody;?>
                    <?php
                    if($showvideos) {
                        foreach ($modelVideo as $video) {
                            if(isset($_POST['video_id']) && $video['id'] == $_POST['video_id']){
                                continue;
                            }
                            ?>
                            <div class="video_item prem">
                                <img class="video_img" src="//img.youtube.com/vi/<?= $video['video_src']; ?>/0.jpg"
                                     alt="img">
                                <div style="text-align: left">
                                    <div style="display: inline-block; float: left;">
                                        <p class="vedeo_art"><?= $video['categoryName']; ?></p>
                                        <p class="vedeo_text"><?= $video['userName']; ?></p>
                                    </div>
                                    <?php $form = ActiveForm::begin(['id' => 'form-signup',
                                        'action' => Url::home().'admin/delete-video',
                                        'method' => 'POST',
                                        'options' => ['class' => 'form-horizontal'],
                                    ]); ?>
                                        <input type="hidden" name="video_src" value="<?= $video['video_src']; ?>">
                                        <input type="hidden" name="video_id" value="<?= $video['id']; ?>">
                                        <button class="btn btn-danger" style="float: right; margin: 11px 0px 0px;">Удалить
                                            <i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    <?php ActiveForm::end(); ?>
                                </div>
                            </div>
                        <?php }
                    }
                    if(count($modelVideo) == 0 || count($modelVideo) == 1 && isset($_POST['video_id'])){
                        echo('<p class="bg-info" style="padding: 15px 0;">Сейчас нет видео для удаления</p>');
                    }
                    ?>

                </div>

            </div>
            <!-- Row End -->

        </div>

    </div>
</div>

views/admin/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Админ панель';
?>
<div class="col-sm-offset-2 col-sm-8  col-md-6  col-lg-6 col-md-offset-3 col-lg-offset-3" style="margin-top: 50px">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: url('../img/pop_reg_bg.jpg');
    background-repeat: no-repeat;
    background-position: left top;background-size:cover;">
                <h1 class="panel-title" style="text-transform: uppercase;
    font: 38px 'BebasNeueRegular';color:white;"><i class="fa fa-lock"></i> Введите логин и пароль</h1>
            </div>
            <div class="panel-body">
                <div class="col-sm-12">
                    <?php $form = ActiveForm::begin([
                        'id' => 'login-form',
                        ]); ?>

                        <?= $form->field($model, 'username')->textInput(['autofocus' => true,'style'=>'padding: 25px !important;'])->label('Логин'); ?>

                        <?= $form->field($model, 'password')->passwordInput(['style'=>'padding: 25px !important;'])->label('Пароль'); ?>

                        <?= $form->field($model, 'rememberMe')->checkbox([
                            'template' => "<div class=\" col-lg-12\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
                        ])->label('Запомнить меня') ?>

                        <div class="form-group">
                            <div class="col-sm-12" style="text-align: center">
                                <?= Html::submitButton('Войти', ['class' => 'up_win_btn', 'name' => 'login-button']) ?>
                            </div>
                        </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
</div>


</div>