controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\City;
use app\models\Country;
use app\models\Video;
use app\models\Category;
use app\models\Usercategory;
use app\models\Usercontact;
use yii\web\HttpException;

class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->redirect('/user/profile');
    }
    
    public function actionProfile()
    {
        if (!\Yii::$app->user->isGuest) {
                $user_id = \Yii::$app->user->id;
                $modelUser = User::find()->where(['id' => $user_id])->one();
            if(\Yii::$app->user->identity->user_status == 1) {
                $specializationCount = Usercategory::find()->where(['user_id' => $user_id])->count();

                return $this->render('profile',[
                    'modelUser' => $modelUser,
                    'specializationCount' => $specializationCount,
                ]);
            }else{
                return $this->render('ban',[
                    'modelUser' => $modelUser,
                ]);
            }
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionSpecialization()
    {
        if (!\Yii::$app->user->isGuest) {
            $user_id = \Yii::$app->user->id;
            $modelUser = User::find()->where(['id' => $user_id])->one();
            if(\Yii::$app->user->identity->user_status == 1) {
                $modelCategory = Category::find()->all();

                $resultCategory = [];
                foreach($modelCategory as $parentCategory){
                    if(($parentCategory['parent_id'] == 0) || $parentCategory['parent_id']== null){
                        $resultCategory[$parentCategory['id']]['name'] = $parentCategory['name'];
                        foreach($modelCategory as $firstChild){
                            if($firstChild['parent_id'] == $parentCategory['id']){
                                $resultCategory[$parentCategory['id']][$firstChild['id']]['name'] = $firstChild['name'];
                                foreach($modelCategory as $lastChild){
                                    if($lastChild['parent_id'] == $firstChild['id']){
                                        $resultCategory[$parentCategory['id']][$firstChild['id']][$lastChild['id']]['name'] = $lastChild['name'];
                                    }
                                }
                            }
                        }                
                    }
                }

                return $this->render('specialization',[
                    'resultCategory' => $resultCategory,
                ]);
            }else{
                return $this->render('ban',[
                    'modelUser' => $modelUser,
                ]);
            }
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionContact()
    {
        if (!\Yii::$app->user->isGuest) {
            $user_id = \Yii::$app->user->id;
            $modelUser = User::find()->where(['id' => $user_id])->one();
            if(\Yii::$app->user->identity->user_status == 1) {
                $modelContact = Usercontact::find()->where(['user_id'=>\Yii::$app->user->id])->one();
                $modelUser = User::find()->where(['id' => \Yii::$app->user->id])->one();
                if($modelContact == null){
                    $modelContact = new Usercontact;
                }
                return $this->render('contact',[
                    'modelContact' => $modelContact,
                    'modelUser' => $modelUser,
                ]);
            }else{
                return $this->render('ban',[
                    'modelUser' => $modelUser,
                ]);
            }
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionVideo()
    {
        if (!\Yii::$app->user->isGuest) {
            $user_id = \Yii::$app->user->id;
            $modelUser = User::find()->where(['id' => $user_id])->one();
            if(\Yii::$app->user->identity->user_status == 1) {
                $query = new Query();
                $query->select(['*', 'id' => 'users_category.id'])
                                ->from('users_category')
                                ->join('LEFT JOIN',
                                                'category',
                                                'category.id = users_category.category_id'
                                        )->where(['users_category.user_id' => \Yii::$app->user->id]);

                $command = $query->createCommand();
                $modelCategoryChoisen = $command->queryAll();
                $arrayCategoryChoisen = ArrayHelper::map($modelCategoryChoisen, 'category_id', 'name');

                return $this->render('video',[
                    'arrayCategoryChoisen' => $arrayCategoryChoisen
                ]);
            }else{
                return $this->render('ban',[
                    'modelUser' => $modelUser,
                ]);
            }
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionAllvideo($username=null)
    {
        if($username != null){
            $modelUser = User::find()->where(['username' => $username])->one();
            if($modelUser != null){
                $arrayCategory = ArrayHelper::map(Category::find()->all(), 'id', 'name');
                return $this->render('allvideo',[
                    'arrayCategory' => $arrayCategory,
                    'username' => $username,
                ]);
            }else{
                throw new HttpException(404);
            }
        }else{
            throw new HttpException(404);
        }
    }
    
    public function actionAjaxsavedataprofile()
    {
        if($_POST['model_name'] == 'contact'){
            $modelContact = Usercontact::find()->where(['user_id' => \Yii::$app->user->id])->one();
            if($modelContact == null){
                $modelContact = new Usercontact;
                $modelContact->user_id = \Yii::$app->user->id;
            }
            if($_POST['field_name'] != 'address_city'){
                $modelContact->$_POST['field_name'] = $_POST['new_value'];
                if($modelContact->save()){
                    $result['status'][] = 'success';
                }else{
                    $result['status'][] = 'error';
                }
            }else{
                $result['status'][] = 'address';
                $modelCity = City::find()->where(['city_name_ru' => $_POST['new_value']])->one();
                if($modelCity != null){
                    $modelContact->$_POST['field_name'] = $_POST['new_value'];
                    if($modelContact->save()){
                        $result['status_address'][] = 'good';
                    }else{
                        $result['status_address'][] = 'error';
                    }
                }else{
                    $result['status_address'][] = 'error';
                }
            }
            
        }elseif($_POST['model_name'] == 'profile'){
            if($_POST['field_name'] != 'password'){
                $modelUser = User::find()->where(['id' => \Yii::$app->user->id])->one();

                $modelUser->scenario = 'update';
                $modelUser->$_POST['field_name'] = $_POST['new_value'];
                if($modelUser->save()){
                    $result['status'][] = 'success';
                }else{
                    $result['status'][] = 'error';
                }
            }else{
                $modelUser = User::find()->where(['id' => \Yii::$app->user->id])->one();
                $modelUser->scenario = 'change_password';
                $modelUser->password_hash = Yii::$app->getSecurity()->generatePasswordHash($_POST['new_value']);
                
                if($modelUser->save()){
                    $result['status'][] = 'success';
                    $result['status_password'][] = 'success';
                }else{
                    $result['status'][] = 'error';
                    $result['status_password'][] = 'error';
                }
            }
            
        }
        echo json_encode($result);
        
    }
    
    public function actionAjaxcategoryuser()
    {
        $category_id = $_POST['category_id'];
        $type_request = $_POST['type_request'];
        $result = [];
        if($type_request == 'checked'){
            $modelUserCategory = new Usercategory();
            $modelUserCategory->user_id = \Yii::$app->user->id;
            $modelUserCategory->category_id = $category_id;

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
$this->title = 'О сервисе';
?>
<div class="site-about container" style="padding-top:20px;">
    <?= $content; ?>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Контакты';
//$this->params['breadcrumbs'][] = $this->title;
?>
<!--<<div class="site-contact">
    h1><?php /*= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; */ ?> 

</div>-->
<div class="site-about container" style="padding-top:20px;">
    <?= $content; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>
<div class="site-error">
<!--
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
-->

<img src="<?= Url::home().'img/404_end.png'; ?>" style="display:block;margin:0 auto;margin-top:120px;max-width:515px;width:100%;" >
</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;
use yii\helpers\Url;
use app\assets\HomevideoAsset;

HomevideoAsset::register($this);

$this->title = 'Baselik';
?>

        <?php 
            if(Yii::$app->session->hasFlash('passwordResetEmailSend')):
                echo Alert::widget([
                    'options' => [
                        'class' => 'alert-info',
                    ],
                    'body' => 'Ссылка для изменения пароля отправлен вам на почту',
                ]);
            endif; 
        ?>

        <div class="serch_wr clf" style="position:relative;">
            <div class="serch_box bs clf">
                <?php $form = ActiveForm::begin(['action' => Url::home().'videosearch','method' => 'get','class' => 'searchForm']); ?>
                    <input AUTOCOMPLETE="off"  type="text" name="input_search" value="" placeholder="Поиск по специальности или услуге...">
                    <button class="clf fr"></button>
                <?php ActiveForm::end(); ?>
                <div class="box_category_list">
                    <ul class="ul_category">
                    </ul>
                </div>
            </div>
            <p class="fl cb clf">Например: <span class="pruklad"><?= $arrayCategory[array_rand($arrayCategory,1)]; ?></span></p>
        </div>

        <div class="profession_box clf">
            <ul class="clf">
                <?php 
                    $k = 0;
                    foreach($modelCategory as $category){
                    $k = $k + 1; ?>
                <li <?php if($k > 2){ echo 'style="display:none;"';} ?>>
                        <?= HTML::a($category->name,'/category/'.$category->url); ?>
                    </li>
                <?php } ?>
            </ul>

            <a class="profession_more fl" style="cursor:pointer;">Ещё профессии</a> 
        </div>

        <div class="reklam_wr clf">
            <div class="reklam_box_r bs fl clf" style="background-image: url('/site/imagetext?<?= time();?>');">
                <p class="reklab_art">Ищешь клиентов?</p>
                <p class="reklam_text">Загрузи свою видеопрезентацию,<br/> покажи себя!</p>
                    <?= HTML::a('Посмотреть рекомендации<br/> по записи видео',Url::home().'recomendation'); ?>
                <?php if(\Yii::$app->user->isGuest){ ?>
                    <a class="reklam_btn registr hb fl" href="#mod">Загрузить видео</a>
                <?php }else{ ?>
                    <?= HTML::a('Загрузить видео','/user/video',['class'=> 'reklam_btn hb fl']); ?>
                <?php } ?>
                <!--<div class="userCount">
                        <p style="color:white;font: 24px 'BebasNeueRegular';"><b>C НАМИ УЖЕ</b></p>
                        <p style="color:white;font: 30px 'BebasNeueRegular';"><b><?= $userCount; ?></b></p>
                        <p style="color:white;font-size:15px;margin-top:-14px;">человек</p>
                    </div>-->
            </div>
            
            
            
            
            <div style="display: none;">
                <div class="box-modal clf" id="cpecForm">
                    <?php $form = ActiveForm::begin(['id' => 'podbor_spec']); ?>
                        <div class="up_win_art">
                            <p>Заявка на подбор специалиста</p>
                        </div>
                        <div class="up_win_input_box">
                            <input type="text" name="name" value="" placeholder="Имя">
                            <input type="email" name="e_mail" value="" placeholder="E-mail">
                            <input type="text" name="telefon" value="" placeholder="Телефон">
                            <?= Html::dropDownList('s_id', null,$arrayCategory,['class'=> 'category_select']) ?>
                        </div>
                        <?= Html::submitButton('Отправить', ['class' => 'up_win_btn podborSpecForm', 'name' => 'login-button']) ?>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            
            
            <div class="reklam_box_l bs fr clf">
                <p class="reklab_art">Ищешь исполнителей?</p>
                <p class="reklam_text">Время не ждет!<br> Просматривай видео  и связывайтесь<br/> со специалистом напрямую!</p>
                <a class="cpecForm" href="#">Или оставьте заявку, и мы<br/> подберём специалиста</a>
            </div>
        </div>

        <div class="video_box videoBoxContent clf" style="margin-top:50px;">
            
        </div>

        <div class="col-sm-12">
            <a class="show_more_video_btn hb cb" href="#">Ещё</a>
        </div>


    

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php
    	if (Yii::$app->getSession()->hasFlash('error')) {
    		echo '<div class="alert alert-danger">'.Yii::$app->getSession()->getFlash('error').'</div>';
    	}
    ?>

    <p class="lead">Do you already have an account on one of these sites? Click the logo to log in with it here:</p>
    <?php echo \nodge\eauth\Widget::widget(array('action' => 'site/login')); ?>
    <hr/>
    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/recomendation.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<style>
    .wrap{
        padding-bottom: 0px !important;
    }
</style>
<div class="row recpmendationDivStyle" >
    <div class="container">
        <div class="col-sm-12">
            <div class="col-lg-6 col-md-6 pull-right recomendationTextBlockOne" style="font-size:16px;">
                Записать привлекательное видео не так сложно, как может показаться на первый взгляд. Для начала будет достаточно даже встроенной камеры телефона - главное, не вздумайте снимать вертикально! Подготовьте заранее текст, обойдитесь без сложных оборотов и технических подробностей своего дела. Пусть это будет речь, которую вам не придётся заучивать - говорите спокойно и без напряжения. 
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-lg-5 col-md-4 pull-right recomendationTextBlockTwo" style="font-size:16px;">
                Хорошо бы снять видео в рабочем антураже, но если такой возможности нет, то лучше встаньте на фоне пустой стены, нежели в жилой комнате с неубранной постелью. Выберите позицию, в которой освещение будет падать на вас, а не на камеру. Если результаты вашей работы можно продемонстрировать на камеру, обязательно сделайте это.
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-lg-5 col-md-4 recomendationTextBlockThree">
                Не забывайте, что вы всегда можете рассчитывать на нашу помощь в качественной съёмке продающего видеоролика. Студия с профессиональным оборудованием и наши специалисты по рекламе обеспечат вам до <b>50% больше шансов на успех!</b>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-6 recomendationTextBlockFoure">
                <h2 style="font: 30px 'BebasNeueRegular';border-bottom:0px;margin-bottom:0px;padding-bottom:0px;text-align:center;"><b>Оставьте свои данные</b></h2>
                <h4 style="text-align:center;">и мы вам обязательно перезвоним</h4>
                
                <input type="text" class="form-control recomendationSendName recomendationBacgroundInput" placeholder="Ваше имя">
                <input type="text" class="form-control recomendationSendTelefon recomendationBacgroundInput" placeholder="Телефон">
                <input type="submit" class="up_win_btn recomendationButtonSend" style="width:100%;background-size: 100%">
                
            </div>
        </div>
    </div>
</div>

views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Запрос на восстановление пароля';
?>
<div class="container">
    <div class="breadcrumbMy">
        <ul class="breadcrumb"><li><a href="<?= Url::home(); ?>">Home</a></li>
            <li class="active"><?= $this->title; ?></li>
        </ul>
    </div>
    <?php 
        if(Yii::$app->session->hasFlash('passwordResetEmailNotSend')):
            echo Alert::widget([
                'options' => [
                    'class' => 'alert-error',
                ],
                'body' => 'Ошибка email',
            ]);
        endif;  
    ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, введите вашу электронную почту. Ссылка для сброса пароля будет отправлена туда</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email')->label('Ваш электронный адрес'); ?>
                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn','style' => 'border-radius: 3px; color: white; background-color: rgb(119, 191, 82);']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Сброс пароля';
?>
<div class="container">
    <div class="breadcrumbMy">
        <ul class="breadcrumb"><li><a href="<?= Url::home(); ?>">Home</a></li>
            <li class="active"><?= $this->title; ?></li>
        </ul>
    </div>
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Пожалуйста, введите новый пароль:</p>
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput()->label('Введите новый пароль'); ?>
                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn','style' => 'border-radius: 3px; color: white; background-color: rgb(119, 191, 82);']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1>Signup</h1>
    
    <?php $form = ActiveForm::begin(['id' => 'form-signup',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-7\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],

            ]); ?>
        <?= $form->field($newModel, 'username') ?>
        <?= $form->field($newModel, 'email') ?>
        <?= $form->field($newModel, 'password')->passwordInput() ?>
        
        <div style="margin-left:150px;" class="form-group">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

    
</div>

views/site/vakancui.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
$this->title = 'Вакансии';
?>
<div class="site-about container" style="padding-top:20px;">
    <?= $content; ?>
</div>

views/site/videosearch.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;
use yii\helpers\Url;
use app\assets\SearchAsset;

SearchAsset::register($this);


$this->title = 'Поиск';
?>
    <div class="serch_wr clf" style="position:relative;">
        <div class="serch_box bs clf">
            <?php $form = ActiveForm::begin(['action' => Url::home().'videosearch','method' => 'get']); ?>
                <input AUTOCOMPLETE="off"  type="text" name="input_search" value="<?= $_GET['input_search']; ?>" placeholder="Поиск по специальности или услуге...">
                <button class="clf fr"></button>
            <?php ActiveForm::end(); ?>
            <div class="box_category_list" style="z-index:999;border: 1px solid #b9b2ad;background-color:white;position:absolute;width:100%;">
                <ul class="ul_category">
                </ul>
            </div>
        </div>
        <p class="fl cb clf">Например: <span class="pruklad"><?= $arrayCategory[array_rand($arrayCategory,1)]; ?></span></p>
        <input type="hidden" class="videosearchtext" value="<?= $_GET['input_search']; ?>">
    </div>

    <div class="video_box videoBoxSearchContent clf" style="margin-top: 20px">

    </div>
    <div class="col-sm-12">
        <a class="show_more_video_btn hb cb" style="display:none;" href="#">Ещё</a>
    </div>